spring:
  application:
    name: productservice
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.8.9:40089/vue
    #url: jdbc:mysql://0.0.0.0:13306/vue

server:
  port: 8080

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  

graphiql:
    mapping: /graphiql
    endpoint:
      graphql: /graphql
    static:
      basePath: /
    enabled: true
    pageTitle: GraphiQL
    cdn:
      enabled: false
      version: 0.13.0
    props:
      variables:
        editorTheme: "solarized light"
